<a href="https://colab.research.google.com/github/Mehnaz-Bashir/Human-Activity-Recognition/blob/main/notebooks/01_Data_Loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Human Activity Recognition using Machine Learning

## Objective

The objective of this project is to develop a machine learning system capable of recognizing human activities using smartphone sensor data. The model will classify activities such as walking, sitting, standing, laying, walking upstairs, and walking downstairs based on accelerometer and gyroscope signals.

In [4]:
import os
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [5]:
import zipfile

zip_path = "/content/UCI HAR Dataset.zip"
extract_path = "/content"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [6]:
import os

print(os.listdir("/content/UCI HAR Dataset"))

['.DS_Store', 'features_info.txt', 'README.txt', 'features.txt', 'activity_labels.txt', 'test', 'train']

In [7]:
print(os.listdir("/content/UCI HAR Dataset/train"))

['subject_train.txt', 'X_train.txt', 'y_train.txt', 'Inertial Signals']

In [8]:
print(os.listdir("/content/UCI HAR Dataset/test"))

['subject_test.txt', 'y_test.txt', 'X_test.txt', 'Inertial Signals']

In [9]:
dataset_path = "/content/UCI HAR Dataset"

In [10]:
features = pd.read_csv(
    os.path.join(dataset_path, "features.txt"),
    sep=r"\s+",
    header=None,
    names=["Index", "Feature"]
)

In [11]:
features.head()

   Index            Feature
0      1  tBodyAcc-mean()-X
1      2  tBodyAcc-mean()-Y
2      3  tBodyAcc-mean()-Z
3      4   tBodyAcc-std()-X
4      5   tBodyAcc-std()-Y

In [12]:
X_train = pd.read_csv(
    os.path.join(dataset_path, "train", "X_train.txt"),
    sep=r"\s+",
    header=None
)

In [13]:
X_train.shape

(7352, 561)

In [20]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,-0.567378,-0.744413,0.852947,0.685845,0.814263,-0.965523,-0.999945,-0.999863,-0.994612,-0.994231,-0.987614,-0.943220,-0.407747,-0.679338,-0.602122,0.929294,-0.853011,0.359910,-0.058526,0.256892,-0.224848,0.264106,-0.095246,0.278851,-0.465085,0.491936,-0.190884,0.376314,0.435129,0.660790,0.963396,-0.140840,0.115375,-0.985250,-0.981708,-0.877625,-0.985001,-0.984416,-0.894677,0.892055,-0.161265,0.124660,0.977436,-0.123213,0.056483,-0.375426,0.899469,-0.970905,-0.975510,-0.984325,-0.988849,-0.917743,-1.0,-1.0,0.113806,-0.590425,0.591146,-0.591773,0.592469,-0.745449,0.720862,-0.712372,0.711300,-0.995112,0.995675,-0.995668,0.991653,0.570222,0.439027,0.986913,0.077996,0.005001,-0.067831,-0.993519,-0.988360,-0.993575,-0.994488,-0.986207,-0.992818,-0.985180,-0.991994,-0.993119,0.989835,0.991957,0.990519,-0.993522,-0.999935,-0.999820,-0.999878,-0.994364,-0.986025,-0.989234,-0.819949,-0.793046,-0.888853,1.000000,-0.220747,0.636831,0.387644,0.241401,-0.052253,0.264177,0.373439,0.341778,-0.569791,0.265399,-0.477875,-0.385300,0.033644,-0.126511,-0.006101,-0.031365,0.107725,-0.985310,-0.976623,-0.992205,-0.984586,-0.976353,-0.992362,-0.867044,-0.933786,-0.747566,0.847308,0.914895,0.830841,-0.967184,-0.999578,-0.999354,-0.999763,-0.983438,-0.978614,-0.992966,0.082632,0.202268,-0.168757,0.096323,-0.274985,0.498644,-0.220317,1.000000,-0.972971,0.316655,0.375726,0.723399,-0.771112,0.690213,-0.331831,0.709584,0.134873,0.301099,-0.099167,-0.055517,-0.061986,-0.992111,-0.992519,-0.992055,-0.992165,-0.994942,-0.992619,-0.990156,-0.986743,-0.992042,0.994429,0.991756,0.989352,-0.994453,-0.999938,-0.999954,-0.999923,-0.992300,-0.996939,-0.992243,-0.589851,-0.688459,-0.572107,0.292376,-0.361998,0.405543,-0.039007,0.989284,-0.414560,0.391603,0.282251,0.927270,-0.572370,0.691619,0.468290,-0.131077,-0.087160,0.336247,-0.959434,-0.950551,-0.957993,-0.946305,-0.992556,-0.959434,-0.998493,-0.957637,-0.232582,-0.173179,-0.022897,0.094832,0.191817,-0.959434,-0.950551,-0.957993,-0.946305,-0.992556,-0.959434,-0.998493,-0.957637,-0.232582,-0.173179,-0.022897,0.094832,0.191817,-0.993306,-0.994336,-0.994500,-0.992784,-0.991208,-0.993306,-0.999892,-0.992934,-0.863415,0.283085,-0.237309,-0.105432,-0.038212,-0.968959,-0.964335,-0.957245,-0.975060,-0.991554,-0.968959,-0.999286,-0.949766,0.072579,0.572511,-0.738602,0.212578,0.433405,-0.994248,-0.991368,-0.993143,-0.988936,-0.993486,-0.994248,-0.999949,-0.994547,-0.619768,0.292840,-0.176889,-0.145779,-0.124072,-0.994783,-0.982984,-0.939269,-0.995422,-0.983133,-0.906165,-0.996889,-0.984519,-0.932082,-0.993756,-0.983163,-0.885054,-0.993962,-0.993446,-0.923428,-0.974733,-0.999968,-0.999689,-0.994891,-0.995926,-0.989709,-0.987991,-0.946357,-0.904748,-0.591302,-1.000000,-1.0,-1.0,0.252483,0.131836,-0.052050,0.142051,-0.150682,-0.220547,-0.558739,0.246769,-0.007416,-0.999963,-0.999987,-0.999979,-0.999962,-0.999932,-0.999725,-0.999670,-0.999986,-0.999969,-0.999977,-0.999870,-0.999776,-0.999971,-0.999919,-0.999657,-0.999860,-0.999867,-0.999863,-0.999738,-0.999732,-0.999493,-0.999814,-0.999682,-0.999839,-0.999738,-0.999612,-0.999687,-0.999839,-0.993592,-0.999476,-0.999662,-0.999642,-0.999293,-0.997892,-0.995932,-0.995146,-0.994740,-0.999688,-0.998925,-0.995671,-0.994877,-0.999454,-0.992332,-0.987170,-0.989696,-0.995821,-0.990936,-0.997052,-0.993805,-0.990519,-0.996993,-0.996737,-0.991975,-0.993242,-0.998349,-0.991108,-0.959885,-0.990515,-0.999935,-0.999820,-0.999884,-0.993026,-0.991373,-0.996240,-1.0,-1.0,-1.0,1.00,-0.24,-1.00,0.870385,0.210697,0.263708,-0.703686,-0.903743,-0.582574,-0.936310,-0.507345,-0.805536,-0.999986,-0.999980,-0.999975,-0.999955,-0.999919,-0.999640,-0.999483,-0.999961,-0.999982,-0.999971,-0.999811,-0.999485,-0.999981,-0.999852,-0.999933,-0.999900,-0.999824,-0.999860,-0.999728,-0.999729,-0.999567,-0.999765,-0.999900,-0.999815,-0.999710,-0.999596,-0.999852,-0.999822,-0.999400,-0.999766,-0.999958,-0.999950,-0.999838,-0.999814,-0.998781,-0.998578,-0.999620,-0.999984,-0.999828,-0.998681,-0.999844,-0.999928,-0.986574,-0.981762,-0.989515,-0.985033,-0.973886,-0.994035,-0.986531,-0.983616,-0.992352,-0.980498,-0.972271,-0.994944,-0.997569,-0.984085,-0.994335,-0.985276,-0.999864,-0.999666,-0.999935,-0.990344,-0.994836,-0.994412,-0.712402,-0.644842,-0.838993,-1.0,-1.000000,-1.000000,-0.257549,0.097947,0.547151,0.377311,0.134092,0.273372,-0.091262,-0.484347,-0.782851,-0.999865,-0.999932,-0.999973,-0.999970,-0.999930,-0.999959,-0.999929,-0.999985,-0.999863,-0.999968,-0.999936,-0.999954,-0.999864,-0.999961,-0.999454,-0.999978,-0.999992,-0.999990,-0.999969,-0.999807,-0.998346,-0.998961,-0.999619,-0.999989,-0.999935,-0.998388,-0.999643,-0.999973,-0.999955,-0.999976,-0.999906,-0.999985,-0.999937,-0.999751,-0.999072,-0.999928,-0.999952,-0.999906,-0.999893,-0.999444,-0.999941,-0.999959,-0.952155,-0.956134,-0.948870,-0.974321,-0.925722,-0.952155,-0.998285,-0.973273,-0.646376,-0.793103,-0.088436,-0.436471,-0.796840,-0.993726,-0.993755,-0.991976,-0.993365,-0.988175,-0.993726,-0.999918,-0.991364,-1.0,-0.936508,0.346989,-0.516080,-0.802760,-0.980135,-0.961309,-0.973653,-0.952264,-0.989498,-0.980135,-0.999240,-0.992656,-0.701291,-1.000000,-0.128989,0.586156,0.374605,-0.991990,-0.990697,-0.989941,-0.992448,-0.991048,-0.991990,-0.999937,-0.990458,-0.871306,-1.000000,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627
1,0.278419,-0.016411,-0.123520,-0.998245,-0.975300,-0.960322,-0.998807,-0.974914,-0.957686,-0.943068,-0.557851,-0.818409,0.849308,0.685845,0.822637,-0.981930,-0.999991,-0.999788,-0.998405,-0.999150,-0.977866,-0.948225,-0.714892,-0.500930,-0.570979,0.611627,-0.329549,0.284213,0.284595,0.115705,-0.090963,0.294310,-0.281211,0.085988,-0.022153,-0.016657,-0.220643,-0.013429,-0.072692,0.579382,0.966561,-0.141551,0.109379,-0.997411,-0.989447,-0.931639,-0.997884,-0.989614,-0.933240,0.892060,-0.161343,0.122586,0.984520,-0.114893,0.102764,-0.383430,0.907829,-0.970583,-0.978500,-0.999188,-0.990029,-0.941685,-1.0,-1.0,-0.210494,-0.410056,0.413856,-0.417567,0.421325,-0.196359,0.125345,-0.105568,0.109090,-0.833882,0.834271,-0.834184,0.830464,-0.831284,-0.865711,0.974386,0.074007,0.005771,0.029377,-0.995548,-0.981064,-0.991846,-0.995632,-0.978938,-0.991277,-0.994545,-0.979068,-0.992257,0.992577,0.991808,0.988539,-0.991394,-0.999960,-0.999640,-0.999845,-0.993863,-0.979435,-0.993384,-0.875096,-0.655362,-0.767381,0.489662,0.070997,0.362714,0.527303,0.149396,0.062925,0.370493,0.413548,0.122216,0.180613,0.047424,0.166573,-0.208772,0.084104,-0.268554,-0.016112,-0.083894,0.100584,-0.983120,-0.989046,-0.989121,-0.986890,-0.989038,-0.989185,-0.864904,-0.953560,-0.745870,0.833721,0.908110,0.828935,-0.980613,-0.999756,-0.999897,-0.999822,-0.992833,-0.989345,-0.990240,0.007469,-0.531157,-0.177445,-0.387681,0.179138,0.210789,-0.140260,-0.047032,-0.064949,0.117687,0.081691,0.042364,-0.149928,0.292619,-0.149429,0.046721,-0.256929,0.169395,-0.110503,-0.044819,-0.059243,-0.989873,-0.997293,-0.993851,-0.989876,-0.997492,-0.993778,-0.991947,-0.997717,-0.994921,0.990486,0.997122,0.994503,-0.995298,-0.999908,-0.999990,-0.999946,-0.990742,-0.997301,-0.993808,-0.600945,-0.748247,-0.608932,-0.193308,-0.067406,0.185619,0.041522,0.072353,-0.035378,0.177606,0.027498,0.182703,-0.167457,0.253251,0.132334,0.293855,-0.018075,-0.343337,-0.979289,-0.976057,-0.978247,-0.978711,-0.995333,-0.979289,-0.999488,-0.981248,-0.441876,0.081569,-0.109366,0.311758,-0.411675,-0.979289,-0.976057,-0.978247,-0.978711,-0.995333,-0.979289,-0.999488,-0.981248,-0.441876,0.081569,-0.109366,0.311758,-0.411675,-0.991253,-0.991694,-0.992716,-0.988661,-0.991208,-0.991253,-0.999845,-0.993485,-0.819928,0.458812,-0.244941,0.056139,-0.458346,-0.980683,-0.983754,-0.982003,-0.984715,-0.991554,-0.980683,-0.999725,-0.982857,-0.192899,-0.225317,-0.017060,0.155777,0.082575,-0.995123,-0.996102,-0.995839,-0.996545,-0.992006,-0.995123,-0.999970,-0.994819,-0.730722,0.209334,-0.178113,-0.103084,-0.043824,-0.997451,-0.976852,-0.973523,-0.998680,-0.974930,-0.955438,-0.997890,-0.976924,-0.968377,-0.999372,-0.973770,-0.948777,-0.998281,-0.992721,-0.989514,-0.985812,-0.999991,-0.999450,-0.998569,-0.994865,-0.980784,-0.985775,-1.000000,-0.904748,-0.758409,0.096774,-1.0,-1.0,0.271309,0.042864,-0.014310,-0.692541,-0.954047,-0.049709,-0.331974,0.056675,-0.289001,-0.999996,-0.999982,-0.999944,-0.999970,-0.999919,-0.999866,-0.999965,-0.999999,-0.999994,-0.999949,-0.999914,-0.999977,-0.999992,-0.999946,-0.999417,-0.999813,-0.999569,-0.999874,-0.999549,-0.999737,-0.999566,-0.999905,-0.999474,-0.999554,-0.999602,-0.999695,-0.999444,-0.999804,-0.998235,-0.999769,-0.999692,-0.999875,-0.999666,-0.999448,-0.998930,-0.998754,-0.998546,-0.999792,-0.999631,-0.998878,-0.998553,-0.999822,-0.995032,-0.981311,-0.989740,-0.996652,-0.982084,-0.992627,-0.994977,-0.982929,-0.991641,-0.997425,-0.984923,-0.993187,-0.997917,-0.982519,-0.986838,-0.989851,-0.999960,-0.999640,-0.999847,-0.992843,-0.985221,-0.991049,-1.0,-1.0,-1.0,-0.32,-0.12,-0.32,0.608514,-0.053676,0.063148,-0.630305,-0.910394,-0.414424,-0.850586,-0.655535,-0.915987,-0.999996,-0.999980,-0.999949,-0.999968,-0.999910,-0.999814,-0.999920,-0.999961,-0.999987,-0.999956,-0.999877,-0.999914,-0.999974,-0.999906,-0.999861,-0.999827,-0.999456,-0.999830,-0.999609,-0.999685,-0.999576,-0.999937,-0.999817,-0.999532,-0.999595,-0.999626,-0.999630,-0.999759,-0.999859,-0.999846,-0.999795,-0.999801,-0.999819,-0.999769,-0.999637,-0.999954,-0.999852,-0.999827,-0.999800,-0.999651,-0.999835,-0.999827,-0.977387,-0.992530,-0.989606,-0.984904,-0.987168,-0.989785,-0.979361,-0.991837,-0.987965,-0.987354,-0.984786,-0.990151,-0.986892,-0.999054,-0.994414,-0.986869,-0.999825,-0.999911,-0.999892,-0.987099,-0.995564,-0.987254,-0.611112,-0.764603,-0.751080,-1.0,-1.000000,-1.000000,-0.048167,-0.401608,-0.068178,-0.458553,-0.797014,0.387569,0.148665,-0.156909,-0.451776,-0.999851,-0.999794,-0.999913,-0.999918,-0.999896,-0.999885,-0.999784,-0.999782,-0.999830,-0.999899,-0.999883,-0.999783,-0.999828,-0.999908,-0.999856,-0.999988,-0.999996,-0.999994,-0.999986,-0.999985,-0.999980,-0.999990,-0.999897,-0.999994,-0.999986,-0.999982,-0.999903,-0.999992,-0.999909,-0.999959,-0.999928,-0.999966,-0.999985,-0.999926,-0.999961,-0.999983,-0.999902,-0.999918,-0.999975,-0.999971,-0.999894,-0.999971,-0.980857,-0.975866,-0.975777,-0.978226,-0.986911,-0.980857,-0.999472,-0.984479,-0.816674,-1.000000,-0.044150,-0.122040,-0.449522,-0.990335,-0.991960,-0.989732,-0.994489,-0.989549,-0.990335,-0.999867,-0.991134,-1.0,-0.841270,0.532061,-0.624871,-0.900160,-0.988296,-0.983322,-0.982659,-0.986321,-0.991829,-0.988296,-0.999811,-0.993979,-0.720683,-0.948718,-0.271958,-0.336310,-0.720015,-0.995854,-0.996399,-0.995442,-0.996866,-0.994440,-0.995854,-0.999981,-0.994544,-1.000000,-1.000000,0.158075,-0.595051,-0.861499,0.053477,-0.007435,-0.732626,0.703511,-0.844788,0.180289,-0.054317
2,0.279653,-0.019467,-0.113462,-0.995380,-0.967187,-0.978944,-0.996520,-0.963668,-0.977469,-0.938692,-0.557851,-0.818409,0.843609,0.682401,0.839344,-0.983478,-0.999969,-0.999660,-0.999470,-0.997130,-0.964810,-0.974675,-0.592235,-0.485821,-0.570979,0.273025,-0.086309,0.337202,-0.164739,0.017150,-0.074507,0.342256,-0.332564,0.239281,-0.136204,0.173863,-0.299493,-0.124698,-0.181105,0.608900,0.966878,-0.142010,0.101884,-0.999574,-0.992866,-0.992917,-0.999635,-0.992605,-0.992934,0.892401,-0.163711,0.094566,0.986770,-0.114893,0.102764,-0.401602,0.908668,-0.970368,-0.981672,-0.999679,-0.992104,-0.992619,-1.0,-1.0,-0.926776,0.002234,0.027481,-0.056728,0.085533,-0.329023,0.270500,-0.254490,0.257598,-0.705039,0.714392,-0.723299,0.728755,-0.181090,0.337936,0.643417,0.073636,0.003104,-0.009046,-0.990743,-0.980956,-0.989687,-0.990933,-0.979300,-0.987238,-0.987077,-0.979068,-0.992257,0.988390,0.991808,0.988539,-0.988148,-0.999894,-0.999636,-0.999795,-0.987846,-0.980145,-0.981911,-0.753629,-0.673274,-0.747107,0.265225,0.188395,0.464583,0.371718,0.082665,-0.004622,0.327470,0.437623,0.257891,0.070030,0.186973,0.246800,-0.120105,-0.110026,-0.039953,-0.031698,-0.102335,0.096127,-0.976292,-0.993552,-0.986379,-0.974922,-0.994122,-0.985786,-0.864904,-0.959049,-0.743277,0.833721,0.905753,0.828935,-0.976280,-0.999693,-0.999828,-0.999822,-0.972354,-0.995144,-0.986831,-0.260943,-1.000000,-0.248371,-0.437156,0.238981,0.145238,-0.113917,0.032312,-0.127879,0.114924,0.125398,0.112092,-0.165645,0.134554,0.184349,-0.010130,0.043312,-0.350646,-0.108486,-0.042410,-0.055829,-0.988462,-0.995632,-0.991532,-0.987868,-0.995725,-0.991596,-0.993359,-0.993800,-0.988963,0.989290,0.997122,0.994143,-0.993415,-0.999887,-0.999980,-0.999916,-0.987130,-0.995428,-0.992776,-0.543635,-0.672957,-0.588410,-0.241151,-0.011377,0.116134,0.089630,0.095986,0.009604,0.095126,0.252887,0.181649,-0.169308,0.132009,0.008197,0.193329,0.073718,-0.314858,-0.983703,-0.988020,-0.988327,-0.986496,-0.995333,-0.983703,-0.999682,-0.985767,-0.599939,0.038049,-0.074212,0.254076,-0.296130,-0.983703,-0.988020,-0.988327,-0.986496,-0.995333,-0.983703,-0.999682,-0.985767,-0.599939,0.038049,-0.074212,0.254076,-0.296130,-0.988531,-0.990397,-0.990650,-0.988661,-0.993012,-0.988531,-0.999790,-0.989984,-0.794884,0.649704,-0.260088,-0.128416,-0.520541,-0.976317,-0.986051,-0.984458,-0.984715,-0.966193,-0.976317,-0.999641,-0.983454,-0.222829,-0.226831,0.059681,0.061476,0.041702,-0.993403,-0.995091,-0.994859,-0.995360,-0.997652,-0.993403,-0.999955,-0.993988,-0.662914,0.328031,-0.154560,-0.220587,-0.107514,-0.993594,-0.972511,-0.983304,-0.996313,-0.965506,-0.977049,-0.994097,-0.971687,-0.982169,-0.998158,-0.963072,-0.968596,-0.997094,-0.989924,-0.990886,-0.985821,-0.999969,-0.999137,-0.999434,-0.988569,-0.977242,-0.981302,-1.000000,-0.815786,-0.813513,-0.935484,-1.0,-1.0,0.124531,-0.064611,0.082677,-0.727227,-0.965419,0.163063,-0.092153,-0.044937,-0.288366,-0.999989,-0.999962,-0.999815,-0.999847,-0.999939,-0.999922,-0.999923,-0.999997,-0.999983,-0.999802,-0.999948,-0.999948,-0.999972,-0.999875,-0.999006,-0.999715,-0.999658,-0.999817,-0.999636,-0.999679,-0.999616,-0.999880,-0.999108,-0.999624,-0.999643,-0.999715,-0.999126,-0.999775,-0.999388,-0.999725,-0.999718,-0.999798,-0.999753,-0.999629,-0.999686,-0.999912,-0.999453,-0.999781,-0.999749,-0.999760,-0.999434,-0.999801,-0.990994,-0.981642,-0.987566,-0.991249,-0.981415,-0.990416,-0.987751,-0.981091,-0.987723,-0.995163,-0.985351,-0.993912,-0.997482,-0.998571,-0.997554,-0.987237,-0.999894,-0.999637,-0.999795,-0.981817,-0.984765,-0.982364,-1.0,-1.0,-1.0,-0.16,-0.48,-0.28,0.115434,-0.193436,0.038254,-0.594759,-0.923541,-0.528934,-0.912985,-0.803407,-0.980133,-0.999994,-0.999944,-0.999827,-0.999841,-0.999922,-0.999906,-0.999874,-0.999997,-0.999963,-0.999804,-0.999923,-0.999875,-0.999909,-0.999843,-0.999820,-0.999744,-0.999559,-0.999839,-0.999667,-0.999627,-0.999704,-0.999993,-0.999732,-0.999611,-0.999618,-0.999744,-0.999613,-0.999773,-0.999871,-0.999784,-0.999740,-0.999787,-0.999772,-0.999626,-0.999487,-0.999996,-0.999803,-0.999792,-0.999721,-0.999514,-0.999775,-0.999787,-0.975433,-0.993715,-0.986756,-0.976642,-0.993399,-0.987328,-0.975609,-0.993707,-0.985030,-0.972901,-0.994986,-0.991283,-0.988312,-0.997233,-0.993636,-0.986009,-0.999673,-0.999962,-0.999846,-0.985536,-0.995392,-0.992551,-0.590987,-0.808287,-0.751080,-1.0,-0.870968,-1.000000,-0.216685,-0.017264,-0.110720,0.090519,-0.244691,-0.429272,-0.812639,-0.391991,-0.767482,-0.999680,-0.999828,-0.999915,-0.999932,-0.999848,-0.999842,-0.999864,-0.999862,-0.999674,-0.999906,-0.999831,-0.999863,-0.999676,-0.999903,-0.999954,-0.999988,-0.999990,-0.999994,-0.999973,-0.999943,-0.999987,-0.999993,-0.999962,-0.999989,-0.999967,-0.999988,-0.999961,-0.999986,-0.999870,-0.999935,-0.999935,-0.999957,-0.999952,-0.999909,-0.999889,-0.999989,-0.999856,-0.999920,-0.999946,-0.999933,-0.999850,-0.999956,-0.987795,-0.989015,-0.985594,-0.993062,-0.989836,-0.987795,-0.999807,-0.989237,-0.907014,-0.862069,0.257899,-0.618725,-0.879685,-0.989280,-0.990867,-0.987274,-0.993179,-0.999890,-0.989280,-0.999845,-0.986658,-1.0,-0.904762,0.660795,-0.724697,-0.928539,-0.989255,-0.986028,-0.984274,-0.990979,-0.995703,-0.989255,-0.999854,-0.993238,-0.736521,-0.794872,-0.212728,-0.535352,-0.871914,-0.995031,-0.995127,-0.994640,-0.996060,-0.995866,-0.995031,-0.999973,-0.993755,-1.000000,-0.555556,0.414503,-0.390748,-0.760104,-0.118559,0.177899,0.100699,0.808529,-0.848933,0.180637,-0.049118

In [21]:
X_train.shape

(7352, 561)

In [24]:
X_train.columns = features["Feature"]

In [25]:
X_train.head()

Feature,tBodyAcc-mean()-X,tBodyAcc-mean()-Y,tBodyAcc-mean()-Z,tBodyAcc-std()-X,tBodyAcc-std()-Y,tBodyAcc-std()-Z,tBodyAcc-mad()-X,tBodyAcc-mad()-Y,tBodyAcc-mad()-Z,tBodyAcc-max()-X,tBodyAcc-max()-Y,tBodyAcc-max()-Z,tBodyAcc-min()-X,tBodyAcc-min()-Y,tBodyAcc-min()-Z,tBodyAcc-sma(),tBodyAcc-energy()-X,tBodyAcc-energy()-Y,tBodyAcc-energy()-Z,tBodyAcc-iqr()-X,tBodyAcc-iqr()-Y,tBodyAcc-iqr()-Z,tBodyAcc-entropy()-X,tBodyAcc-entropy()-Y,tBodyAcc-entropy()-Z,"tBodyAcc-arCoeff()-X,1","tBodyAcc-arCoeff()-X,2","tBodyAcc-arCoeff()-X,3","tBodyAcc-arCoeff()-X,4","tBodyAcc-arCoeff()-Y,1","tBodyAcc-arCoeff()-Y,2","tBodyAcc-arCoeff()-Y,3","tBodyAcc-arCoeff()-Y,4","tBodyAcc-arCoeff()-Z,1","tBodyAcc-arCoeff()-Z,2","tBodyAcc-arCoeff()-Z,3","tBodyAcc-arCoeff()-Z,4","tBodyAcc-correlation()-X,Y","tBodyAcc-correlation()-X,Z","tBodyAcc-correlation()-Y,Z",tGravityAcc-mean()-X,tGravityAcc-mean()-Y,tGravityAcc-mean()-Z,tGravityAcc-std()-X,tGravityAcc-std()-Y,tGravityAcc-std()-Z,tGravityAcc-mad()-X,tGravityAcc-mad()-Y,tGravityAcc-mad()-Z,tGravityAcc-max()-X,tGravityAcc-max()-Y,tGravityAcc-max()-Z,tGravityAcc-min()-X,tGravityAcc-min()-Y,tGravityAcc-min()-Z,tGravityAcc-sma(),tGravityAcc-energy()-X,tGravityAcc-energy()-Y,tGravityAcc-energy()-Z,tGravityAcc-iqr()-X,tGravityAcc-iqr()-Y,tGravityAcc-iqr()-Z,tGravityAcc-entropy()-X,tGravityAcc-entropy()-Y,tGravityAcc-entropy()-Z,"tGravityAcc-arCoeff()-X,1","tGravityAcc-arCoeff()-X,2","tGravityAcc-arCoeff()-X,3","tGravityAcc-arCoeff()-X,4","tGravityAcc-arCoeff()-Y,1","tGravityAcc-arCoeff()-Y,2","tGravityAcc-arCoeff()-Y,3","tGravityAcc-arCoeff()-Y,4","tGravityAcc-arCoeff()-Z,1","tGravityAcc-arCoeff()-Z,2","tGravityAcc-arCoeff()-Z,3","tGravityAcc-arCoeff()-Z,4","tGravityAcc-correlation()-X,Y","tGravityAcc-correlation()-X,Z","tGravityAcc-correlation()-Y,Z",tBodyAccJerk-mean()-X,tBodyAccJerk-mean()-Y,tBodyAccJerk-mean()-Z,tBodyAccJerk-std()-X,tBodyAccJerk-std()-Y,tBodyAccJerk-std()-Z,tBodyAccJerk-mad()-X,tBodyAccJerk-mad()-Y,tBodyAccJerk-mad()-Z,tBodyAccJerk-max()-X,tBodyAccJerk-max()-Y,tBodyAccJerk-max()-Z,tBodyAccJerk-min()-X,tBodyAccJerk-min()-Y,tBodyAccJerk-min()-Z,tBodyAccJerk-sma(),tBodyAccJerk-energy()-X,tBodyAccJerk-energy()-Y,tBodyAccJerk-energy()-Z,tBodyAccJerk-iqr()-X,tBodyAccJerk-iqr()-Y,tBodyAccJerk-iqr()-Z,tBodyAccJerk-entropy()-X,tBodyAccJerk-entropy()-Y,tBodyAccJerk-entropy()-Z,"tBodyAccJerk-arCoeff()-X,1","tBodyAccJerk-arCoeff()-X,2","tBodyAccJerk-arCoeff()-X,3","tBodyAccJerk-arCoeff()-X,4","tBodyAccJerk-arCoeff()-Y,1","tBodyAccJerk-arCoeff()-Y,2","tBodyAccJerk-arCoeff()-Y,3","tBodyAccJerk-arCoeff()-Y,4","tBodyAccJerk-arCoeff()-Z,1","tBodyAccJerk-arCoeff()-Z,2","tBodyAccJerk-arCoeff()-Z,3","tBodyAccJerk-arCoeff()-Z,4","tBodyAccJerk-correlation()-X,Y","tBodyAccJerk-correlation()-X,Z","tBodyAccJerk-correlation()-Y,Z",tBodyGyro-mean()-X,tBodyGyro-mean()-Y,tBodyGyro-mean()-Z,tBodyGyro-std()-X,tBodyGyro-std()-Y,tBodyGyro-std()-Z,tBodyGyro-mad()-X,tBodyGyro-mad()-Y,tBodyGyro-mad()-Z,tBodyGyro-max()-X,tBodyGyro-max()-Y,tBodyGyro-max()-Z,tBodyGyro-min()-X,tBodyGyro-min()-Y,tBodyGyro-min()-Z,tBodyGyro-sma(),tBodyGyro-energy()-X,tBodyGyro-energy()-Y,tBodyGyro-energy()-Z,tBodyGyro-iqr()-X,tBodyGyro-iqr()-Y,tBodyGyro-iqr()-Z,tBodyGyro-entropy()-X,tBodyGyro-entropy()-Y,tBodyGyro-entropy()-Z,"tBodyGyro-arCoeff()-X,1","tBodyGyro-arCoeff()-X,2","tBodyGyro-arCoeff()-X,3","tBodyGyro-arCoeff()-X,4","tBodyGyro-arCoeff()-Y,1","tBodyGyro-arCoeff()-Y,2","tBodyGyro-arCoeff()-Y,3","tBodyGyro-arCoeff()-Y,4","tBodyGyro-arCoeff()-Z,1","tBodyGyro-arCoeff()-Z,2","tBodyGyro-arCoeff()-Z,3","tBodyGyro-arCoeff()-Z,4","tBodyGyro-correlation()-X,Y","tBodyGyro-correlation()-X,Z","tBodyGyro-correlation()-Y,Z",tBodyGyroJerk-mean()-X,tBodyGyroJerk-mean()-Y,tBodyGyroJerk-mean()-Z,tBodyGyroJerk-std()-X,tBodyGyroJerk-std()-Y,tBodyGyroJerk-std()-Z,tBodyGyroJerk-mad()-X,tBodyGyroJerk-mad()-Y,tBodyGyroJerk-mad()-Z,tBodyGyroJerk-max()-X,tBodyGyroJerk-max()-Y,tBodyGyroJerk-max()-Z,tBodyGyroJerk-min()-X,tBodyGyroJerk-min()-Y,tBodyGyroJerk-min()-Z,tBodyGyroJerk-sma(),tBodyGyroJerk-energy()-X,tBodyGyroJerk-energy()-Y,tBodyGyroJerk-energy()-Z,tBodyGyroJerk-iqr()-X,tBodyGyroJerk-iqr()-Y,tBodyGyroJerk-iqr()-Z,tBodyGyroJerk-entropy()-X,tBodyGyroJerk-entropy()-Y,tBodyGyroJerk-entropy()-Z,"tBodyGyroJerk-arCoeff()-X,1","tBodyGyroJerk-arCoeff()-X,2","tBodyGyroJerk-arCoeff()-X,3","tBodyGyroJerk-arCoeff()-X,4","tBodyGyroJerk-arCoeff()-Y,1","tBodyGyroJerk-arCoeff()-Y,2","tBodyGyroJerk-arCoeff()-Y,3","tBodyGyroJerk-arCoeff()-Y,4","tBodyGyroJerk-arCoeff()-Z,1","tBodyGyroJerk-arCoeff()-Z,2","tBodyGyroJerk-arCoeff()-Z,3","tBodyGyroJerk-arCoeff()-Z,4","tBodyGyroJerk-correlation()-X,Y","tBodyGyroJerk-correlation()-X,Z","tBodyGyroJerk-correlation()-Y,Z",tBodyAccMag-mean(),tBodyAccMag-std(),tBodyAccMag-mad(),tBodyAccMag-max(),tBodyAccMag-min(),tBodyAccMag-sma(),tBodyAccMag-energy(),tBodyAccMag-iqr(),tBodyAccMag-entropy(),tBodyAccMag-arCoeff()1,tBodyAccMag-arCoeff()2,tBodyAccMag-arCoeff()3,tBodyAccMag-arCoeff()4,tGravityAccMag-mean(),tGravityAccMag-std(),tGravityAccMag-mad(),tGravityAccMag-max(),tGravityAccMag-min(),tGravityAccMag-sma(),tGravityAccMag-energy(),tGravityAccMag-iqr(),tGravityAccMag-entropy(),tGravityAccMag-arCoeff()1,tGravityAccMag-arCoeff()2,tGravityAccMag-arCoeff()3,tGravityAccMag-arCoeff()4,tBodyAccJerkMag-mean(),tBodyAccJerkMag-std(),tBodyAccJerkMag-mad(),tBodyAccJerkMag-max(),tBodyAccJerkMag-min(),tBodyAccJerkMag-sma(),tBodyAccJerkMag-energy(),tBodyAccJerkMag-iqr(),tBodyAccJerkMag-entropy(),tBodyAccJerkMag-arCoeff()1,tBodyAccJerkMag-arCoeff()2,tBodyAccJerkMag-arCoeff()3,tBodyAccJerkMag-arCoeff()4,tBodyGyroMag-mean(),tBodyGyroMag-std(),tBodyGyroMag-mad(),tBodyGyroMag-max(),tBodyGyroMag-min(),tBodyGyroMag-sma(),tBodyGyroMag-energy(),tBodyGyroMag-iqr(),tBodyGyroMag-entropy(),tBodyGyroMag-arCoeff()1,tBodyGyroMag-arCoeff()2,tBodyGyroMag-arCoeff()3,tBodyGyroMag-arCoeff()4,tBodyGyroJerkMag-mean(),tBodyGyroJerkMag-std(),tBodyGyroJerkMag-mad(),tBodyGyroJerkMag-max(),tBodyGyroJerkMag-min(),tBodyGyroJerkMag-sma(),tBodyGyroJerkMag-energy(),tBodyGyroJerkMag-iqr(),tBodyGyroJerkMag-entropy(),tBodyGyroJerkMag-arCoeff()1,tBodyGyroJerkMag-arCoeff()2,tBodyGyroJerkMag-arCoeff()3,tBodyGyroJerkMag-arCoeff()4,fBodyAcc-mean()-X,fBodyAcc-mean()-Y,fBodyAcc-mean()-Z,fBodyAcc-std()-X,fBodyAcc-std()-Y,fBodyAcc-std()-Z,fBodyAcc-mad()-X,fBodyAcc-mad()-Y,fBodyAcc-mad()-Z,fBodyAcc-max()-X,fBodyAcc-max()-Y,fBodyAcc-max()-Z,fBodyAcc-min()-X,fBodyAcc-min()-Y,fBodyAcc-min()-Z,fBodyAcc-sma(),fBodyAcc-energy()-X,fBodyAcc-energy()-Y,fBodyAcc-energy()-Z,fBodyAcc-iqr()-X,fBodyAcc-iqr()-Y,fBodyAcc-iqr()-Z,fBodyAcc-entropy()-X,fBodyAcc-entropy()-Y,fBodyAcc-entropy()-Z,fBodyAcc-maxInds-X,fBodyAcc-maxInds-Y,fBodyAcc-maxInds-Z,fBodyAcc-meanFreq()-X,fBodyAcc-meanFreq()-Y,fBodyAcc-meanFreq()-Z,fBodyAcc-skewness()-X,fBodyAcc-kurtosis()-X,fBodyAcc-skewness()-Y,fBodyAcc-kurtosis()-Y,fBodyAcc-skewness()-Z,fBodyAcc-kurtosis()-Z,"fBodyAcc-bandsEnergy()-1,8","fBodyAcc-bandsEnergy()-9,16","fBodyAcc-bandsEnergy()-17,24","fBodyAcc-bandsEnergy()-25,32","fBodyAcc-bandsEnergy()-33,40","fBodyAcc-bandsEnergy()-41,48","fBodyAcc-bandsEnergy()-49,56","fBodyAcc-bandsEnergy()-57,64","fBodyAcc-bandsEnergy()-1,16","fBodyAcc-bandsEnergy()-17,32","fBodyAcc-bandsEnergy()-33,48","fBodyAcc-bandsEnergy()-49,64","fBodyAcc-bandsEnergy()-1,24","fBodyAcc-bandsEnergy()-25,48","fBodyAcc-bandsEnergy()-1,8","fBodyAcc-bandsEnergy()-9,16","fBodyAcc-bandsEnergy()-17,24","fBodyAcc-bandsEnergy()-25,32","fBodyAcc-bandsEnergy()-33,40","fBodyAcc-bandsEnergy()-41,48","fBodyAcc-bandsEnergy()-49,56","fBodyAcc-bandsEnergy()-57,64","fBodyAcc-bandsEnergy()-1,16","fBodyAcc-bandsEnergy()-17,32","fBodyAcc-bandsEnergy()-33,48","fBodyAcc-bandsEnergy()-49,64","fBodyAcc-bandsEnergy()-1,24","fBodyAcc-bandsEnergy()-25,48","fBodyAcc-bandsEnergy()-1,8","fBodyAcc-bandsEnergy()-9,16","fBodyAcc-bandsEnergy()-17,24","fBodyAcc-bandsEnergy()-25,32","fBodyAcc-bandsEnergy()-33,40","fBodyAcc-bandsEnergy()-41,48","fBodyAcc-bandsEnergy()-49,56","fBodyAcc-bandsEnergy()-57,64","fBodyAcc-bandsEnergy()-1,16","fBodyAcc-bandsEnergy()-17,32","fBodyAcc-bandsEnergy()-33,48","fBodyAcc-bandsEnergy()-49,64","fBodyAcc-bandsEnergy()-1,24","fBodyAcc-bandsEnergy()-25,48",fBodyAccJerk-mean()-X,fBodyAccJerk-mean()-Y,fBodyAccJerk-mean()-Z,fBodyAccJerk-std()-X,fBodyAccJerk-std()-Y,fBodyAccJerk-std()-Z,fBodyAccJerk-mad()-X,fBodyAccJerk-mad()-Y,fBodyAccJerk-mad()-Z,fBodyAccJerk-max()-X,fBodyAccJerk-max()-Y,fBodyAccJerk-max()-Z,fBodyAccJerk-min()-X,fBodyAccJerk-min()-Y,fBodyAccJerk-min()-Z,fBodyAccJerk-sma(),fBodyAccJerk-energy()-X,fBodyAccJerk-energy()-Y,fBodyAccJerk-energy()-Z,fBodyAccJerk-iqr()-X,fBodyAccJerk-iqr()-Y,fBodyAccJerk-iqr()-Z,fBodyAccJerk-entropy()-X,fBodyAccJerk-entropy()-Y,fBodyAccJerk-entropy()-Z,fBodyAccJerk-maxInds-X,fBodyAccJerk-maxInds-Y,fBodyAccJerk-maxInds-Z,fBodyAccJerk-meanFreq()-X,fBodyAccJerk-meanFreq()-Y,fBodyAccJerk-meanFreq()-Z,fBodyAccJerk-skewness()-X,fBodyAccJerk-kurtosis()-X,fBodyAccJerk-skewness()-Y,fBodyAccJerk-kurtosis()-Y,fBodyAccJerk-skewness()-Z,fBodyAccJerk-kurtosis()-Z,"fBodyAccJerk-bandsEnergy()-1,8","fBodyAccJerk-bandsEnergy()-9,16","fBodyAccJerk-bandsEnergy()-17,24","fBodyAccJerk-bandsEnergy()-25,32","fBodyAccJerk-bandsEnergy()-33,40","fBodyAccJerk-bandsEnergy()-41,48","fBodyAccJerk-bandsEnergy()-49,56","fBodyAccJerk-bandsEnergy()-57,64","fBodyAccJerk-bandsEnergy()-1,16","fBodyAccJerk-bandsEnergy()-17,32","fBodyAccJerk-bandsEnergy()-33,48","fBodyAccJerk-bandsEnergy()-49,64","fBodyAccJerk-bandsEnergy()-1,24","fBodyAccJerk-bandsEnergy()-25,48","fBodyAccJerk-bandsEnergy()-1,8","fBodyAccJerk-bandsEnergy()-9,16","fBodyAccJerk-bandsEnergy()-17,24","fBodyAccJerk-bandsEnergy()-25,32","fBodyAccJerk-bandsEnergy()-33,40","fBodyAccJerk-bandsEnergy()-41,48","fBodyAccJerk-bandsEnergy()-49,56","fBodyAccJerk-bandsEnergy()-57,64","fBodyAccJerk-bandsEnergy()-1,16","fBodyAccJerk-bandsEnergy()-17,32","fBodyAccJerk-bandsEnergy()-33,48","fBodyAccJerk-bandsEnergy()-49,64","fBodyAccJerk-bandsEnergy()-1,24","fBodyAccJerk-bandsEnergy()-25,48","fBodyAccJerk-bandsEnergy()-1,8","fBodyAccJerk-bandsEnergy()-9,16","fBodyAccJerk-bandsEnergy()-17,24","fBodyAccJerk-bandsEnergy()-25,32","fBodyAccJerk-bandsEnergy()-33,40","fBodyAccJerk-bandsEnergy()-41,48","fBodyAccJerk-bandsEnergy()-49,56","fBodyAccJerk-bandsEnergy()-57,64","fBodyAccJerk-bandsEnergy()-1,16","fBodyAccJerk-bandsEnergy()-17,32","fBodyAccJerk-bandsEnergy()-33,48","fBodyAccJerk-bandsEnergy()-49,64","fBodyAccJerk-bandsEnergy()-1,24","fBodyAccJerk-bandsEnergy()-25,48",fBodyGyro-mean()-X,fBodyGyro-mean()-Y,fBodyGyro-mean()-Z,fBodyGyro-std()-X,fBodyGyro-std()-Y,fBodyGyro-std()-Z,fBodyGyro-mad()-X,fBodyGyro-mad()-Y,fBodyGyro-mad()-Z,fBodyGyro-max()-X,fBodyGyro-max()-Y,fBodyGyro-max()-Z,fBodyGyro-min()-X,fBodyGyro-min()-Y,fBodyGyro-min()-Z,fBodyGyro-sma(),fBodyGyro-energy()-X,fBodyGyro-energy()-Y,fBodyGyro-energy()-Z,fBodyGyro-iqr()-X,fBodyGyro-iqr()-Y,fBodyGyro-iqr()-Z,fBodyGyro-entropy()-X,fBodyGyro-entropy()-Y,fBodyGyro-entropy()-Z,fBodyGyro-maxInds-X,fBodyGyro-maxInds-Y,fBodyGyro-maxInds-Z,fBodyGyro-meanFreq()-X,fBodyGyro-meanFreq()-Y,fBodyGyro-meanFreq()-Z,fBodyGyro-skewness()-X,fBodyGyro-kurtosis()-X,fBodyGyro-skewness()-Y,fBodyGyro-kurtosis()-Y,fBodyGyro-skewness()-Z,fBodyGyro-kurtosis()-Z,"fBodyGyro-bandsEnergy()-1,8","fBodyGyro-bandsEnergy()-9,16","fBodyGyro-bandsEnergy()-17,24","fBodyGyro-bandsEnergy()-25,32","fBodyGyro-bandsEnergy()-33,40","fBodyGyro-bandsEnergy()-41,48","fBodyGyro-bandsEnergy()-49,56","fBodyGyro-bandsEnergy()-57,64","fBodyGyro-bandsEnergy()-1,16","fBodyGyro-bandsEnergy()-17,32","fBodyGyro-bandsEnergy()-33,48","fBodyGyro-bandsEnergy()-49,64","fBodyGyro-bandsEnergy()-1,24","fBodyGyro-bandsEnergy()-25,48","fBodyGyro-bandsEnergy()-1,8","fBodyGyro-bandsEnergy()-9,16","fBodyGyro-bandsEnergy()-17,24","fBodyGyro-bandsEnergy()-25,32","fBodyGyro-bandsEnergy()-33,40","fBodyGyro-bandsEnergy()-41,48","fBodyGyro-bandsEnergy()-49,56","fBodyGyro-bandsEnergy()-57,64","fBodyGyro-bandsEnergy()-1,16","fBodyGyro-bandsEnergy()-17,32","fBodyGyro-bandsEnergy()-33,48","fBodyGyro-bandsEnergy()-49,64","fBodyGyro-bandsEnergy()-1,24","fBodyGyro-bandsEnergy()-25,48","fBodyGyro-bandsEnergy()-1,8","fBodyGyro-bandsEnergy()-9,16","fBodyGyro-bandsEnergy()-17,24","fBodyGyro-bandsEnergy()-25,32","fBodyGyro-bandsEnergy()-33,40","fBodyGyro-bandsEnergy()-41,48","fBodyGyro-bandsEnergy()-49,56","fBodyGyro-bandsEnergy()-57,64","fBodyGyro-bandsEnergy()-1,16","fBodyGyro-bandsEnergy()-17,32","fBodyGyro-bandsEnergy()-33,48","fBodyGyro-bandsEnergy()-49,64","fBodyGyro-bandsEnergy()-1,24","fBodyGyro-bandsEnergy()-25,48",fBodyAccMag-mean(),fBodyAccMag-std(),fBodyAccMag-mad(),fBodyAccMag-max(),fBodyAccMag-min(),fBodyAccMag-sma(),fBodyAccMag-energy(),fBodyAccMag-iqr(),fBodyAccMag-entropy(),fBodyAccMag-maxInds,fBodyAccMag-meanFreq(),fBodyAccMag-skewness(),fBodyAccMag-kurtosis(),fBodyBodyAccJerkMag-mean(),fBodyBodyAccJerkMag-std(),fBodyBodyAccJerkMag-mad(),fBodyBodyAccJerkMag-max(),fBodyBodyAccJerkMag-min(),fBodyBodyAccJerkMag-sma(),fBodyBodyAccJerkMag-energy(),fBodyBodyAccJerkMag-iqr(),fBodyBodyAccJerkMag-entropy(),fBodyBodyAccJerkMag-maxInds,fBodyBodyAccJerkMag-meanFreq(),fBodyBodyAccJerkMag-skewness(),fBodyBodyAccJerkMag-kurtosis(),fBodyBodyGyroMag-mean(),fBodyBodyGyroMag-std(),fBodyBodyGyroMag-mad(),fBodyBodyGyroMag-max(),fBodyBodyGyroMag-min(),fBodyBodyGyroMag-sma(),fBodyBodyGyroMag-energy(),fBodyBodyGyroMag-iqr(),fBodyBodyGyroMag-entropy(),fBodyBodyGyroMag-maxInds,fBodyBodyGyroMag-meanFreq(),fBodyBodyGyroMag-skewness(),fBodyBodyGyroMag-kurtosis(),fBodyBodyGyroJerkMag-mean(),fBodyBodyGyroJerkMag-std(),fBodyBodyGyroJerkMag-mad(),fBodyBodyGyroJerkMag-max(),fBodyBodyGyroJerkMag-min(),fBodyBodyGyroJerkMag-sma(),fBodyBodyGyroJerkMag-energy(),fBodyBodyGyroJerkMag-iqr(),fBodyBodyGyroJerkMag-entropy(),fBodyBodyGyroJerkMag-maxInds,fBodyBodyGyroJerkMag-meanFreq(),fBodyBodyGyroJerkMag-skewness(),fBodyBodyGyroJerkMag-kurtosis(),"angle(tBodyAccMean,gravity)","angle(tBodyAccJerkMean),gravityMean)","angle(tBodyGyroMean,gravityMean)","angle(tBodyGyroJerkMean,gravityMean)","angle(X,gravityMean)","angle(Y,gravityMean)","angle(Z,gravityMean)"
0,0.288585,-0.020294,-0.132905,-0.995279,-0.983111,-0.913526,-0.995112,-0.983185,-0.923527,-0.934724,-0.567378,-0.744413,0.852947,0.685845,0.814263,-0.965523,-0.999945,-0.999863,-0.994612,-0.994231,-0.987614,-0.943220,-0.407747,-0.679338,-0.602122,0.929294,-0.853011,0.359910,-0.058526,0.256892,-0.224848,0.264106,-0.095246,0.278851,-0.465085,0.491936,-0.190884,0.376314,0.435129,0.660790,0.963396,-0.140840,0.115375,-0.985250,-0.981708,-0.877625,-0.985001,-0.984416,-0.894677,0.892055,-0.161265,0.124660,0.977436,-0.123213,0.056483,-0.375426,0.899469,-0.970905,-0.975510,-0.984325,-0.988849,-0.917743,-1.0,-1.0,0.113806,-0.590425,0.591146,-0.591773,0.592469,-0.745449,0.720862,-0.712372,0.711300,-0.995112,0.995675,-0.995668,0.991653,0.570222,0.439027,0.986913,0.077996,0.005001,-0.067831,-0.993519,-0.988360,-0.993575,-0.994488,-0.986207,-0.992818,-0.985180,-0.991994,-0.993119,0.989835,0.991957,0.990519,-0.993522,-0.999935,-0.999820,-0.999878,-0.994364,-0.986025,-0.989234,-0.819949,-0.793046,-0.888853,1.000000,-0.220747,0.636831,0.387644,0.241401,-0.052253,0.264177,0.373439,0.341778,-0.569791,0.265399,-0.477875,-0.385300,0.033644,-0.126511,-0.006101,-0.031365,0.107725,-0.985310,-0.976623,-0.992205,-0.984586,-0.976353,-0.992362,-0.867044,-0.933786,-0.747566,0.847308,0.914895,0.830841,-0.967184,-0.999578,-0.999354,-0.999763,-0.983438,-0.978614,-0.992966,0.082632,0.202268,-0.168757,0.096323,-0.274985,0.498644,-0.220317,1.000000,-0.972971,0.316655,0.375726,0.723399,-0.771112,0.690213,-0.331831,0.709584,0.134873,0.301099,-0.099167,-0.055517,-0.061986,-0.992111,-0.992519,-0.992055,-0.992165,-0.994942,-0.992619,-0.990156,-0.986743,-0.992042,0.994429,0.991756,0.989352,-0.994453,-0.999938,-0.999954,-0.999923,-0.992300,-0.996939,-0.992243,-0.589851,-0.688459,-0.572107,0.292376,-0.361998,0.405543,-0.039007,0.989284,-0.414560,0.391603,0.282251,0.927270,-0.572370,0.691619,0.468290,-0.131077,-0.087160,0.336247,-0.959434,-0.950551,-0.957993,-0.946305,-0.992556,-0.959434,-0.998493,-0.957637,-0.232582,-0.173179,-0.022897,0.094832,0.191817,-0.959434,-0.950551,-0.957993,-0.946305,-0.992556,-0.959434,-0.998493,-0.957637,-0.232582,-0.173179,-0.022897,0.094832,0.191817,-0.993306,-0.994336,-0.994500,-0.992784,-0.991208,-0.993306,-0.999892,-0.992934,-0.863415,0.283085,-0.237309,-0.105432,-0.038212,-0.968959,-0.964335,-0.957245,-0.975060,-0.991554,-0.968959,-0.999286,-0.949766,0.072579,0.572511,-0.738602,0.212578,0.433405,-0.994248,-0.991368,-0.993143,-0.988936,-0.993486,-0.994248,-0.999949,-0.994547,-0.619768,0.292840,-0.176889,-0.145779,-0.124072,-0.994783,-0.982984,-0.939269,-0.995422,-0.983133,-0.906165,-0.996889,-0.984519,-0.932082,-0.993756,-0.983163,-0.885054,-0.993962,-0.993446,-0.923428,-0.974733,-0.999968,-0.999689,-0.994891,-0.995926,-0.989709,-0.987991,-0.946357,-0.904748,-0.591302,-1.000000,-1.0,-1.0,0.252483,0.131836,-0.052050,0.142051,-0.150682,-0.220547,-0.558739,0.246769,-0.007416,-0.999963,-0.999987,-0.999979,-0.999962,-0.999932,-0.999725,-0.999670,-0.999986,-0.999969,-0.999977,-0.999870,-0.999776,-0.999971,-0.999919,-0.999657,-0.999860,-0.999867,-0.999863,-0.999738,-0.999732,-0.999493,-0.999814,-0.999682,-0.999839,-0.999738,-0.999612,-0.999687,-0.999839,-0.993592,-0.999476,-0.999662,-0.999642,-0.999293,-0.997892,-0.995932,-0.995146,-0.994740,-0.999688,-0.998925,-0.995671,-0.994877,-0.999454,-0.992332,-0.987170,-0.989696,-0.995821,-0.990936,-0.997052,-0.993805,-0.990519,-0.996993,-0.996737,-0.991975,-0.993242,-0.998349,-0.991108,-0.959885,-0.990515,-0.999935,-0.999820,-0.999884,-0.993026,-0.991373,-0.996240,-1.0,-1.0,-1.0,1.00,-0.24,-1.00,0.870385,0.210697,0.263708,-0.703686,-0.903743,-0.582574,-0.936310,-0.507345,-0.805536,-0.999986,-0.999980,-0.999975,-0.999955,-0.999919,-0.999640,-0.999483,-0.999961,-0.999982,-0.999971,-0.999811,-0.999485,-0.999981,-0.999852,-0.999933,-0.999900,-0.999824,-0.999860,-0.999728,-0.999729,-0.999567,-0.999765,-0.999900,-0.999815,-0.999710,-0.999596,-0.999852,-0.999822,-0.999400,-0.999766,-0.999958,-0.999950,-0.999838,-0.999814,-0.998781,-0.998578,-0.999620,-0.999984,-0.999828,-0.998681,-0.999844,-0.999928,-0.986574,-0.981762,-0.989515,-0.985033,-0.973886,-0.994035,-0.986531,-0.983616,-0.992352,-0.980498,-0.972271,-0.994944,-0.997569,-0.984085,-0.994335,-0.985276,-0.999864,-0.999666,-0.999935,-0.990344,-0.994836,-0.994412,-0.712402,-0.644842,-0.838993,-1.0,-1.000000,-1.000000,-0.257549,0.097947,0.547151,0.377311,0.134092,0.273372,-0.091262,-0.484347,-0.782851,-0.999865,-0.999932,-0.999973,-0.999970,-0.999930,-0.999959,-0.999929,-0.999985,-0.999863,-0.999968,-0.999936,-0.999954,-0.999864,-0.999961,-0.999454,-0.999978,-0.999992,-0.999990,-0.999969,-0.999807,-0.998346,-0.998961,-0.999619,-0.999989,-0.999935,-0.998388,-0.999643,-0.999973,-0.999955,-0.999976,-0.999906,-0.999985,-0.999937,-0.999751,-0.999072,-0.999928,-0.999952,-0.999906,-0.999893,-0.999444,-0.999941,-0.999959,-0.952155,-0.956134,-0.948870,-0.974321,-0.925722,-0.952155,-0.998285,-0.973273,-0.646376,-0.793103,-0.088436,-0.436471,-0.796840,-0.993726,-0.993755,-0.991976,-0.993365,-0.988175,-0.993726,-0.999918,-0.991364,-1.0,-0.936508,0.346989,-0.516080,-0.802760,-0.980135,-0.961309,-0.973653,-0.952264,-0.989498,-0.980135,-0.999240,-0.992656,-0.701291,-1.000000,-0.128989,0.586156,0.374605,-0.991990,-0.990697,-0.989941,-0.992448,-0.991048,-0.991990,-0.999937,-0.990458,-0.871306,-1.000000,-0.074323,-0.298676,-0.710304,-0.112754,0.030400,-0.464761,-0.018446,-0.841247,0.179941,-0.058627

In [26]:
print("Shape of X_train:", X_train.shape)

Shape of X_train: (7352, 561)

In [27]:
X_train.columns[:10]

Index(['tBodyAcc-mean()-X', 'tBodyAcc-mean()-Y', 'tBodyAcc-mean()-Z',
       'tBodyAcc-std()-X', 'tBodyAcc-std()-Y', 'tBodyAcc-std()-Z',
       'tBodyAcc-mad()-X', 'tBodyAcc-mad()-Y', 'tBodyAcc-mad()-Z',
       'tBodyAcc-max()-X'],
      dtype='object', name='Feature')